name: Cypress CI

on:
  push:
    branches:
    - main  
  pull_request:
    branches:
      - main  
  schedule:
    - cron: '*/2 * * * *'  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

